docs: documentacao events/myeduzz
eduzz/eduzz-webhook-docs pull request #5
Opened 2024-02-05 18:39 UTC by gustavomfranzin

2024-02-05 21:06 UTC, GSouzaT submitted a review, later dismissed

2024-02-06 11:36 UTC, caferrari requested changes

2024-02-06 11:36 UTC, caferrari commented on events/myeduzz/commission_processed.md
> +        "currency": "BRL",
segue o padrão do valor sempre dentro de um value object

```
{
          "id": "789451",
          "name": "Coproducer name",
          "commission": {
              "currency": "BRL",
              "value": 10.0
          }
}
```

2024-05-28 14:53 UTC, caferrari submitted a review, later dismissed

2024-06-12 13:05 UTC, ASOCezar approved these changes

2024-06-12 13:06 UTC, heitorc1 approved these changes

2024-06-12 14:02 UTC, merged